# Generated by Django 3.2.4 on 2022-02-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=122, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('years_taught', models.CharField(blank=True, max_length=10, null=True)),
                ('is_pro', models.CharField(default='null', max_length=3)),
                ('subjects', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uni_deadline', models.DateField(blank=True, null=True)),
                ('program_applied', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('images', models.ImageField(blank=True, default='cute_baby.gif', upload_to='images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('subjects', models.ManyToManyField(to='home.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLoginInfo',
            fields=[
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('roll_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, default='null', max_length=10, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='studentdata',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacherinfo'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentlogininfo'),
        ),
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadership', models.BooleanField(default=False)),
                ('hardworking', models.BooleanField(default=False)),
                ('social', models.BooleanField(default=False)),
                ('teamwork', models.BooleanField(default=False)),
                ('friendly', models.BooleanField(default=False)),
                ('intern', models.BooleanField(default=False)),
                ('presentation', models.CharField(blank=True, max_length=50, null=True)),
                ('extracirricular', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervised_project', models.CharField(blank=True, max_length=100, null=True)),
                ('final_project', models.CharField(blank=True, max_length=200, null=True)),
                ('deployed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(blank=True, max_length=100, null=True)),
                ('paper_link', models.CharField(blank=True, max_length=200, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.FileField(blank=True, upload_to='transcript/')),
                ('CV', models.FileField(blank=True, upload_to='cv/')),
                ('Photo', models.ImageField(blank=True, upload_to='student_photo/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.CharField(blank=True, max_length=50, null=True)),
                ('tentative_ranking', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentdata')),
            ],
        ),
    ]
